package proxmox

import (
	"context"
	"errors"
	"iter"
)

type (
	BackupScheduleInterface interface {
		// Create creates a new backup schedule and returns the generated ID.
		Create(context.Context, ConfigBackupSchedule) (BackupScheduleID, error)

		// Delete deletes the specified backup schedule.
		// Returns true if the schedule was deleted, false if it did not exist.
		Delete(context.Context, BackupScheduleID) (bool, error)

		// Exists checks whether the specified backup schedule exists.
		Exists(context.Context, BackupScheduleID) (bool, error)

		// List returns all backup schedules.
		List(ctx context.Context) (RawBackupSchedules, error)

		// Read returns the config of the specified backup schedule.
		Read(context.Context, BackupScheduleID) (RawBackupSchedule, error)

		// Set creates the backup schedule if it does not exist, or updates it if it does.
		// Returns the ID of the backup schedule (existing or newly created).
		Set(context.Context, ConfigBackupSchedule) (BackupScheduleID, error)

		// Update updates an existing backup schedule. ConfigBackupSchedule.ID must be set.
		Update(context.Context, ConfigBackupSchedule) error
	}

	backupScheduleClient struct {
		api *clientAPI
	}
)

var _ BackupScheduleInterface = (*backupScheduleClient)(nil)

func (c *backupScheduleClient) Create(ctx context.Context, config ConfigBackupSchedule) (BackupScheduleID, error) {
	if err := config.validateCreate(); err != nil {
		return "", err
	}
	return config.create(ctx, c.api)
}

func (c *backupScheduleClient) Delete(ctx context.Context, id BackupScheduleID) (bool, error) {
	if err := id.Validate(); err != nil {
		return false, err
	}
	return id.delete(ctx, c.api)
}

func (c *backupScheduleClient) Exists(ctx context.Context, id BackupScheduleID) (bool, error) {
	if err := id.Validate(); err != nil {
		return false, err
	}
	return id.exists(ctx, c.api)
}

func (c *backupScheduleClient) List(ctx context.Context) (RawBackupSchedules, error) {
	return backupScheduleList(ctx, c.api)
}

func (c *backupScheduleClient) Read(ctx context.Context, id BackupScheduleID) (RawBackupSchedule, error) {
	if err := id.Validate(); err != nil {
		return nil, err
	}
	return id.read(ctx, c.api)
}

func (c *backupScheduleClient) Set(ctx context.Context, config ConfigBackupSchedule) (BackupScheduleID, error) {
	if config.ID != "" {
		if err := config.ID.Validate(); err != nil {
			return "", err
		}
		exists, err := config.ID.exists(ctx, c.api)
		if err != nil {
			return "", err
		}
		if exists {
			if err := config.validateUpdate(); err != nil {
				return "", err
			}
			return config.ID, config.update(ctx, c.api)
		}
	}
	if err := config.validateCreate(); err != nil {
		return "", err
	}
	return config.create(ctx, c.api)
}

func (c *backupScheduleClient) Update(ctx context.Context, config ConfigBackupSchedule) error {
	if err := config.ID.Validate(); err != nil {
		return err
	}
	if err := config.validateUpdate(); err != nil {
		return err
	}
	return config.update(ctx, c.api)
}

// ConfigBackupSchedule represents a Proxmox scheduled backup job (/cluster/backup).
type ConfigBackupSchedule struct {
	// ID is the backup job identifier generated by Proxmox. Empty on create; set when reading or updating.
	ID BackupScheduleID `json:"id,omitempty"`

	// Schedule is the Proxmox calendar event string (e.g. "daily 2:00", "sun 3:00"). Required on create.
	Schedule *string `json:"schedule,omitempty"`

	// Storage is the target storage ID. Required on create.
	Storage *StorageName `json:"storage,omitempty"`

	// Mode is the backup mode: snapshot, suspend, or stop.
	Mode *string `json:"mode,omitempty"`

	// Compress is the compression algorithm: 0, gzip, lzo, or zstd.
	Compress *string `json:"compress,omitempty"`

	// VMIDs is a comma-separated list of VM/CT IDs to back up.
	VMIDs *string `json:"vmid,omitempty"`

	// All, when true, backs up all VMs and CTs.
	All *bool `json:"all,omitempty"`

	// Pool restricts the backup to VMs/CTs in this pool.
	Pool *PoolName `json:"pool,omitempty"`

	// Enabled specifies whether the backup job is active. Defaults to true on Proxmox.
	Enabled *bool `json:"enabled,omitempty"`

	// Node restricts the backup job to run only on the specified node.
	Node *NodeName `json:"node,omitempty"`

	// Mailto is a comma-separated list of email addresses for notifications.
	Mailto *string `json:"mailto,omitempty"`

	// MailNotification controls when notification email is sent: always or failure.
	MailNotification *string `json:"mailnotification,omitempty"`

	// NotesTemplate is the template string used to generate notes for each backup.
	NotesTemplate *string `json:"notes-template,omitempty"`

	// PruneBackups defines the retention settings for the backup job (e.g. "keep-last=3").
	PruneBackups *string `json:"prune-backups,omitempty"`

	// Protected marks the backup archives as protected, preventing automatic removal.
	Protected *bool `json:"protected,omitempty"`

	// Comment is a human-readable description of the backup job.
	Comment *string `json:"comment,omitempty"`
}

// mapToApiCreate builds the params map for a POST /cluster/backup request.
// Only non-nil fields are included so that Proxmox defaults are not overwritten.
func (config ConfigBackupSchedule) mapToApiCreate() map[string]any {
	params := map[string]any{}
	if config.Schedule != nil {
		params[backupScheduleApiKeySchedule] = *config.Schedule
	}
	if config.Storage != nil {
		params[backupScheduleApiKeyStorage] = string(*config.Storage)
	}
	if config.Mode != nil {
		params[backupScheduleApiKeyMode] = *config.Mode
	}
	if config.Compress != nil {
		params[backupScheduleApiKeyCompress] = *config.Compress
	}
	if config.VMIDs != nil {
		params[backupScheduleApiKeyVMIDs] = *config.VMIDs
	}
	if config.All != nil {
		params[backupScheduleApiKeyAll] = Btoi(*config.All)
	}
	if config.Pool != nil {
		params[backupScheduleApiKeyPool] = string(*config.Pool)
	}
	if config.Enabled != nil {
		params[backupScheduleApiKeyEnabled] = Btoi(*config.Enabled)
	}
	if config.Node != nil {
		params[backupScheduleApiKeyNode] = string(*config.Node)
	}
	if config.Mailto != nil {
		params[backupScheduleApiKeyMailto] = *config.Mailto
	}
	if config.MailNotification != nil {
		params[backupScheduleApiKeyMailNotification] = *config.MailNotification
	}
	if config.NotesTemplate != nil {
		params[backupScheduleApiKeyNotesTemplate] = *config.NotesTemplate
	}
	if config.PruneBackups != nil {
		params[backupScheduleApiKeyPruneBackups] = *config.PruneBackups
	}
	if config.Protected != nil {
		params[backupScheduleApiKeyProtected] = Btoi(*config.Protected)
	}
	if config.Comment != nil {
		params[backupScheduleApiKeyComment] = *config.Comment
	}
	return params
}

// mapToApiUpdate builds the params map for a PUT /cluster/backup/{id} request.
// Non-nil fields are sent with their value; nil optional fields are sent as empty
// string so that Proxmox clears them.
func (config ConfigBackupSchedule) mapToApiUpdate() map[string]any {
	params := map[string]any{}
	setString := func(k string, v *string) {
		if v != nil {
			params[k] = *v
		} else {
			params[k] = ""
		}
	}
	setStorageName := func(k string, v *StorageName) {
		if v != nil {
			params[k] = string(*v)
		} else {
			params[k] = ""
		}
	}
	setPoolName := func(k string, v *PoolName) {
		if v != nil {
			params[k] = string(*v)
		} else {
			params[k] = ""
		}
	}
	setNodeName := func(k string, v *NodeName) {
		if v != nil {
			params[k] = string(*v)
		} else {
			params[k] = ""
		}
	}
	setBool := func(k string, v *bool) {
		if v != nil {
			params[k] = Btoi(*v)
		}
	}

	setString(backupScheduleApiKeySchedule, config.Schedule)
	setStorageName(backupScheduleApiKeyStorage, config.Storage)
	setString(backupScheduleApiKeyMode, config.Mode)
	setString(backupScheduleApiKeyCompress, config.Compress)
	setString(backupScheduleApiKeyVMIDs, config.VMIDs)
	setBool(backupScheduleApiKeyAll, config.All)
	setPoolName(backupScheduleApiKeyPool, config.Pool)
	setBool(backupScheduleApiKeyEnabled, config.Enabled)
	setNodeName(backupScheduleApiKeyNode, config.Node)
	setString(backupScheduleApiKeyMailto, config.Mailto)
	setString(backupScheduleApiKeyMailNotification, config.MailNotification)
	setString(backupScheduleApiKeyNotesTemplate, config.NotesTemplate)
	setString(backupScheduleApiKeyPruneBackups, config.PruneBackups)
	setBool(backupScheduleApiKeyProtected, config.Protected)
	setString(backupScheduleApiKeyComment, config.Comment)
	return params
}

func (config ConfigBackupSchedule) create(ctx context.Context, c *clientAPI) (BackupScheduleID, error) {
	return c.createBackupSchedule(ctx, config.mapToApiCreate())
}

func (config ConfigBackupSchedule) update(ctx context.Context, c *clientAPI) error {
	return c.updateBackupSchedule(ctx, config.ID, config.mapToApiUpdate())
}

func (config ConfigBackupSchedule) validateCreate() error {
	if config.Schedule == nil || *config.Schedule == "" {
		return errors.New(ConfigBackupSchedule_Error_ScheduleRequired)
	}
	if config.Storage == nil {
		return errors.New(ConfigBackupSchedule_Error_StorageRequired)
	}
	return config.validateUpdate()
}

func (config ConfigBackupSchedule) validateUpdate() error {
	if config.Mode != nil {
		if err := ValidateStringInArray(backupScheduleModes, *config.Mode, "mode"); err != nil {
			return err
		}
	}
	if config.Compress != nil {
		if err := ValidateStringInArray(backupScheduleCompressions, *config.Compress, "compress"); err != nil {
			return err
		}
	}
	if config.MailNotification != nil {
		if err := ValidateStringInArray(backupScheduleMailNotifications, *config.MailNotification, "mailnotification"); err != nil {
			return err
		}
	}
	return nil
}

// BackupScheduleID is the identifier for a Proxmox backup schedule job (e.g. "backup-XXXXXXXX").
type BackupScheduleID string

const (
	BackupScheduleID_Error_Empty string = "variable of type (BackupScheduleID) may not be empty"
)

func (id BackupScheduleID) String() string { return string(id) }

func (id BackupScheduleID) Validate() error {
	if id == "" {
		return errors.New(BackupScheduleID_Error_Empty)
	}
	return nil
}

func (id BackupScheduleID) delete(ctx context.Context, c *clientAPI) (bool, error) {
	if err := c.deleteBackupSchedule(ctx, id); err != nil {
		var apiErr *ApiError
		if errors.As(err, &apiErr) {
			if apiErr.Message == backupScheduleNotFoundMessage(id) {
				return false, nil
			}
		}
		return false, err
	}
	return true, nil
}

func (id BackupScheduleID) exists(ctx context.Context, c *clientAPI) (bool, error) {
	_, err := id.read(ctx, c)
	if err != nil {
		var apiErr *ApiError
		if errors.As(err, &apiErr) {
			if apiErr.Message == backupScheduleNotFoundMessage(id) {
				return false, nil
			}
		}
		return false, err
	}
	return true, nil
}

func (id BackupScheduleID) read(ctx context.Context, c *clientAPI) (*rawBackupSchedule, error) {
	raw, err := c.getBackupScheduleConfig(ctx, id)
	if err != nil {
		return nil, err
	}
	return &rawBackupSchedule{a: raw, id: id}, nil
}

func backupScheduleNotFoundMessage(id BackupScheduleID) string {
	return "backup job '" + id.String() + "' does not exist"
}

func backupScheduleList(ctx context.Context, c *clientAPI) (*rawBackupSchedules, error) {
	params, err := c.listBackupSchedules(ctx)
	if err != nil {
		return nil, err
	}
	return &rawBackupSchedules{a: params}, nil
}

// RawBackupSchedules is the result of listing all backup schedule jobs.
type (
	RawBackupSchedules interface {
		AsArray() []RawBackupSchedule
		AsMap() map[BackupScheduleID]RawBackupSchedule
		Iter() iter.Seq[RawBackupSchedule]
		Len() int
	}
	rawBackupSchedules struct{ a []any }
)

var _ RawBackupSchedules = (*rawBackupSchedules)(nil)

func (r *rawBackupSchedules) AsArray() []RawBackupSchedule {
	schedules := make([]RawBackupSchedule, len(r.a))
	for i := range r.a {
		raw := rawBackupSchedule{a: r.a[i].(map[string]any)}
		if v, ok := raw.a[backupScheduleApiKeyID].(string); ok {
			raw.id = BackupScheduleID(v)
		}
		schedules[i] = &raw
	}
	return schedules
}

func (r *rawBackupSchedules) AsMap() map[BackupScheduleID]RawBackupSchedule {
	schedules := make(map[BackupScheduleID]RawBackupSchedule, len(r.a))
	for i := range r.a {
		raw := rawBackupSchedule{a: r.a[i].(map[string]any)}
		if v, ok := raw.a[backupScheduleApiKeyID].(string); ok {
			raw.id = BackupScheduleID(v)
		}
		schedules[raw.id] = &raw
	}
	return schedules
}

func (r *rawBackupSchedules) Iter() iter.Seq[RawBackupSchedule] {
	return func(yield func(RawBackupSchedule) bool) {
		for i := range r.a {
			raw := rawBackupSchedule{a: r.a[i].(map[string]any)}
			if v, ok := raw.a[backupScheduleApiKeyID].(string); ok {
				raw.id = BackupScheduleID(v)
			}
			if !yield(&raw) {
				return
			}
		}
	}
}

func (r *rawBackupSchedules) Len() int { return len(r.a) }

// RawBackupSchedule is the result of reading a single backup schedule job.
type (
	RawBackupSchedule interface {
		Get() ConfigBackupSchedule
		GetID() BackupScheduleID
		GetSchedule() string
		GetStorage() StorageName
		GetMode() string
		GetCompress() string
		GetVMIDs() string
		GetAll() bool
		GetPool() PoolName
		GetEnabled() bool
		GetNode() NodeName
		GetMailto() string
		GetMailNotification() string
		GetNotesTemplate() string
		GetPruneBackups() string
		GetProtected() bool
		GetComment() string
	}
	rawBackupSchedule struct {
		a  map[string]any
		id BackupScheduleID
	}
)

var _ RawBackupSchedule = (*rawBackupSchedule)(nil)

func (r *rawBackupSchedule) Get() ConfigBackupSchedule {
	schedule := r.GetSchedule()
	storage := r.GetStorage()
	mode := r.GetMode()
	compress := r.GetCompress()
	vmids := r.GetVMIDs()
	all := r.GetAll()
	pool := r.GetPool()
	enabled := r.GetEnabled()
	node := r.GetNode()
	mailto := r.GetMailto()
	mailNotification := r.GetMailNotification()
	notesTemplate := r.GetNotesTemplate()
	pruneBackups := r.GetPruneBackups()
	protected := r.GetProtected()
	comment := r.GetComment()
	config := ConfigBackupSchedule{
		ID:               r.id,
		Schedule:         &schedule,
		Storage:          &storage,
		Mode:             &mode,
		Compress:         &compress,
		VMIDs:            &vmids,
		All:              &all,
		Pool:             &pool,
		Enabled:          &enabled,
		Node:             &node,
		Mailto:           &mailto,
		MailNotification: &mailNotification,
		NotesTemplate:    &notesTemplate,
		PruneBackups:     &pruneBackups,
		Protected:        &protected,
		Comment:          &comment,
	}
	return config
}

func (r *rawBackupSchedule) GetID() BackupScheduleID {
	if r.id != "" {
		return r.id
	}
	if v, ok := r.a[backupScheduleApiKeyID].(string); ok {
		return BackupScheduleID(v)
	}
	return ""
}

func (r *rawBackupSchedule) GetSchedule() string {
	if v, ok := r.a[backupScheduleApiKeySchedule].(string); ok {
		return v
	}
	return ""
}

func (r *rawBackupSchedule) GetStorage() StorageName {
	if v, ok := r.a[backupScheduleApiKeyStorage].(string); ok {
		return StorageName(v)
	}
	return ""
}

func (r *rawBackupSchedule) GetMode() string {
	if v, ok := r.a[backupScheduleApiKeyMode].(string); ok {
		return v
	}
	return ""
}

func (r *rawBackupSchedule) GetCompress() string {
	if v, ok := r.a[backupScheduleApiKeyCompress].(string); ok {
		return v
	}
	return ""
}

func (r *rawBackupSchedule) GetVMIDs() string {
	if v, ok := r.a[backupScheduleApiKeyVMIDs].(string); ok {
		return v
	}
	return ""
}

func (r *rawBackupSchedule) GetAll() bool {
	if v, ok := r.a[backupScheduleApiKeyAll]; ok {
		switch val := v.(type) {
		case float64:
			return val == 1
		case bool:
			return val
		}
	}
	return false
}

func (r *rawBackupSchedule) GetPool() PoolName {
	if v, ok := r.a[backupScheduleApiKeyPool].(string); ok {
		return PoolName(v)
	}
	return ""
}

func (r *rawBackupSchedule) GetEnabled() bool {
	if v, ok := r.a[backupScheduleApiKeyEnabled]; ok {
		switch val := v.(type) {
		case float64:
			return val == 1
		case bool:
			return val
		}
	}
	return true // Proxmox defaults to enabled
}

func (r *rawBackupSchedule) GetNode() NodeName {
	if v, ok := r.a[backupScheduleApiKeyNode].(string); ok {
		return NodeName(v)
	}
	return ""
}

func (r *rawBackupSchedule) GetMailto() string {
	if v, ok := r.a[backupScheduleApiKeyMailto].(string); ok {
		return v
	}
	return ""
}

func (r *rawBackupSchedule) GetMailNotification() string {
	if v, ok := r.a[backupScheduleApiKeyMailNotification].(string); ok {
		return v
	}
	return ""
}

func (r *rawBackupSchedule) GetNotesTemplate() string {
	if v, ok := r.a[backupScheduleApiKeyNotesTemplate].(string); ok {
		return v
	}
	return ""
}

func (r *rawBackupSchedule) GetPruneBackups() string {
	if v, ok := r.a[backupScheduleApiKeyPruneBackups].(string); ok {
		return v
	}
	return ""
}

func (r *rawBackupSchedule) GetProtected() bool {
	if v, ok := r.a[backupScheduleApiKeyProtected]; ok {
		switch val := v.(type) {
		case float64:
			return val == 1
		case bool:
			return val
		}
	}
	return false
}

func (r *rawBackupSchedule) GetComment() string {
	if v, ok := r.a[backupScheduleApiKeyComment].(string); ok {
		return v
	}
	return ""
}

// Proxmox API field names for the backup schedule endpoint.
const (
	backupScheduleApiKeyAll             string = "all"
	backupScheduleApiKeyComment         string = "comment"
	backupScheduleApiKeyCompress        string = "compress"
	backupScheduleApiKeyEnabled         string = "enabled"
	backupScheduleApiKeyID              string = "id"
	backupScheduleApiKeyMailNotification string = "mailnotification"
	backupScheduleApiKeyMailto          string = "mailto"
	backupScheduleApiKeyMode            string = "mode"
	backupScheduleApiKeyNode            string = "node"
	backupScheduleApiKeyNotesTemplate   string = "notes-template"
	backupScheduleApiKeyPool            string = "pool"
	backupScheduleApiKeyProtected       string = "protected"
	backupScheduleApiKeyPruneBackups    string = "prune-backups"
	backupScheduleApiKeySchedule        string = "schedule"
	backupScheduleApiKeyStorage         string = "storage"
	backupScheduleApiKeyVMIDs           string = "vmid"
)

// Error message constants for ConfigBackupSchedule.
const (
	ConfigBackupSchedule_Error_ScheduleRequired string = "schedule is required to create a backup schedule"
	ConfigBackupSchedule_Error_StorageRequired  string = "storage is required to create a backup schedule"
)

// Valid values for backup schedule fields.
var (
	backupScheduleModes            = []string{"snapshot", "suspend", "stop"}
	backupScheduleCompressions     = []string{"0", "gzip", "lzo", "zstd"}
	backupScheduleMailNotifications = []string{"always", "failure"}
)
